# Generated by Django 5.0.6 on 2024-06-13 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='desctiption',
            new_name='tododescription',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='endtime',
            new_name='todoendtime',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='starttime',
            new_name='todostarttime',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='title',
            new_name='todotitle',
        ),
    ]
